### PR TITLE
fix object type

### PR DESCRIPTION
**Pull request by gallynero**
Check if the array is a object arrayable

### CODE REVIEW

**Comment by jailtonsc** [comment]
Thanks for the contribution, when I have a little time I will check if the code does not give any problem.

**Comment by timhaak** [comment]
Hi this help fix it for me running on Laravel 5.4

**Comment by gallynero** [comment]
Thank you for your comment and I am very happy to have been of help

**Comment by jailtonsc** [comment]
Sorry for the delay. Thanks for the contribution I already include in the package.

**Pull request merged**
